### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by rsj123** [changetjut/ProxySpider#2]
Traceback (most recent call last):
  File "C:\Users\rsj\Downloads\ProxySpider-master\httpproxy.py", line 87, in <module>
    proxynum = getProxyList("http://www.xicidaili.com/nn/")
  File "C:\Users\rsj\Downloads\ProxySpider-master\httpproxy.py", line 30, in getProxyList
    trs = soup.find('table', id='ip_list').find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by changetjut** [comment]
请使用最新版本
